### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by keszybz** [pysb/pysb#101]
Are there any plans? Would potential patches to make code python2/3 compatible be accepted?

**Comment by alubbock** [comment]
One workaround for the lack of `<>` would be to use named infix operators, like so: http://code.activestate.com/recipes/384122/

**Comment by keszybz** [comment]
On Mon, Jun 29, 2015 at 03:04:42PM -0700, alubbock wrote:
> One workaround for the lack of `<>` would be to use named infix operators, like so: http://code.activestate.com/recipes/384122/

I think that's too much of hack.

**Comment by jmuhlich** [comment]
If we wanted to go down that road, I'd rather go all in and use macropy to
pull off some *really* cool tricks. But I think macropy is too "out there"
to make it an absolute requirement. Even if we had optional support for it,
we would still need a more "conservative" approach to replacing <>. Perhaps
one of the bitwise operators, as they have the right precedence level. "&"
could work, with the mnemonic "it goes forwards AND backwards". This would
also free up the equality/comparison operators, making them usable for
actual comparisons again.

Another option is to remove the whole notion of reversibility from
RuleExpression, only provide the >> operator, and require the reversibility
to be specified as an explicit argument to the Rule constructor with a
default of True. So an irreversible rule would look like this: Rule(A>>B,
kf, reversible=False) .

**Comment by keszybz** [comment]
Hm, the operator issue notwithstanding, what about merging #112 (or something similar), without the operator change for now. The result would not be Python3 compatible, but would be very close, and Python3 users could do the patch to change the operator on their own. If that would be acceptable, I'd update #112 (I presume it doesn't apply cleanly anymore) and remove operator change from it.

**Comment by jmuhlich** [comment]
Yes, let's do that.
