### ISSUE TITLE
dummy issue to test slack integration

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#121]
This is the body of the issue.

**Comment by jmuhlich** [comment]
here is a comment.

**Comment by jmuhlich** [comment]
will it notify on comments? maybe someone else has to comment.

**Comment by dpwrussell** [comment]
Test comment

**Comment by jmuhlich** [comment]
ok now the webhook is sending **all** events

**Comment by jmuhlich** [comment]
ok this looks good. closing.
