### ISSUE TITLE
ComplexPattern.is_equivalent_to doesn't canonicalize properly

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#13]
The literal site_conditions comparison requires bond numbering to be identical, so some sort of canonicalization of that numbering is necessary.

**Comment by johnbachman** [comment]
Wait, are you sure this is the issue you meant to close with that PR?

**Comment by jmuhlich** [comment]
Oh no. Alex wrote "closes #13" to reference LoLab-VU/pysb #13, not pysb/pysb #13! I don't know how to avoid that from happening...

**Comment by alubbock** [comment]
I'll use the long format, LoLab-VU/pysb#13, in the future. Sorry for the mix up!
