### ISSUE TITLE
preconfigured VM

### ISSUE THREAD

**Issue by gskrish2001** [pysb/pysb#131]
I have gone through the process of installing all the dependencies into a virtual environment in a Ubuntu 14.04 Virtual machine (using VirtualBox). After going through that it did not work, had to do with Bionetgen (2.2.6 precompiled version was used) and PySB. Can someone provide a more recent Ubuntu VM which can be scaled and virtualbox guest additions can be added from the GUI. Everything had to be done from the command line and even after that the resolution etc in lucid could not be set properly to match those available with computers available today, so one can work with effectively. New to github so I don't know if this is grammar used here or whether this is the venue. Any help would be useful

**Comment by jmuhlich** [comment]
We provide a Dockerfile -- maybe that would be an easier route to getting a working VM. I don't have a lot of experience with Docker, but maybe @alubbock could comment on how easy it would be to use our Dockerfile as a basis for an Ubuntu desktop VM.

**Comment by gskrish2001** [comment]
Hi Jeremy,
Thanks for your reply. I do have a working VM, the one that has been provided. When I installed all the components on Ubuntu 14.04, it started but I think, later versions of some of the associated components (scipy) do not work well with PySB. Do you know if a new ubuntu VM with PySB will be released by your team. The drawback with the current VM is that I am somehow not able to make it go fullscreen (in my laptop of desktop because screen size is restrained and cannot be changed) and its hard to work with a small screen. But, thank you for responding anyway. Any other help is appreciated.

**Comment by alubbock** [comment]
@gskrish2001 Our Docker container, which Jeremy mentioned above, is an Ubuntu-based VM, but instead of a GUI it uses [Jupyter](https://jupyter.org) (formerly called iPython Notebook) through your web browser. If you'd like to give it a try, [here are installation instructions](https://github.com/LoLab-VU/pysb/wiki/Installation). Let me know if you have any questions.

**Comment by gskrish2001** [comment]
Hi alubbock
Thank you for the information. I am going to try the docker method. Thank you very much.

**Comment by alubbock** [comment]
Since the VM is no longer a supported environment for PySB, I'll close this ticket. Please open a separate issue if you have any problems with our current Docker or Anaconda installation methods, described here: http://pysb.readthedocs.io/en/stable/installation.html
