### ISSUE TITLE
Create test_kappa.py

### ISSUE THREAD

**Issue by alubbock** [pysb/pysb#155]
We need a unit test suite for `pysb/kappa.py` to increase code coverage, which is currently <20%.

**Comment by alubbock** [comment]
Travis support for Kappa and `test_kappa.py` with Kappa expressions tests are in PR #117. Probably best to merge that before proceeding with this issue.

**Comment by johnbachman** [comment]
Yes. Actually I've significantly refactored and improved upon PR #117 in a local branch (kappa_fixes), getting that merged is on my short list of development tasks.

**Comment by jmuhlich** [comment]
`kappa.py` and `generator/kappa.py` are both at >80% coverage now so I think we can close this.
