### ISSUE TITLE
odesolve(...verbose=True) hangs under python 3

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#164]
test_integrate.py's test_integrate_with_expression calls `odesolve` with verbose=True, and it seems like the communication with BNG hangs when waiting for the end of the output. This happens on python 3.4.3 on homebrew on the mac I'm using right now, not sure about other platforms yet. There shouldn't be any verbose=True integrator calls in the test suite, so that's the quick fix to make the tests run to completion, but we do need to figure out what's wrong with the verbose=True code in bng.py under python 3 for general usage.

**Comment by jmuhlich** [comment]
Oops, #167 shouldn't close this. Try to remember to reopen after the PR merge auto-closes it. :)

**Comment by alubbock** [comment]
Has this been resolved? Works for me on Python 3.5.2 macOS/homebrew.

**Comment by alubbock** [comment]
The full test suite seems to run fine on Python 3.6.4 on macOS for me. There have been a lot of changes to the simulation engine since this issue was filed in September 2015, so I'll presume this has been fixed somewhere along the line. Please reopen if you're still experiencing issues.

Thanks.
