### ISSUE TITLE
Use mkdtemp rather than NamedTemporaryFile in BNG interface code

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#179]
To encapsulate the temporary input/runtime/output files needed for interfacing with and running BNG, doing everything in a directory created with `tempfile.mkdtemp` would be more secure than a series of files based on just a `NamedTemporaryFile` base name. (Thanks to @dkoes for discussion in #178 )

**Comment by alubbock** [comment]
I agree that `mkdtemp` would be best practice - for security, mitigating potential race conditions (however unlikely) and easier cleanup (just delete the directory when done). The `NamedTemporaryFile` calls can then be replaced with a standard file open call (there's only ever one BNGL file per BNG console/file interface 'session').

This should be fairly straightforward. I'll self assign and get it done.
