### ISSUE TITLE
Unable to run reversible reactions

### ISSUE THREAD

**Issue by artgoldberg** [pysb/pysb#191]
We are unable to run PySB models from the tutorial or examples that have reversible reactions. E.g., neither hello_pysb.py nor the mymodel.py model runs. Running mymodel.py from the tutorial generates:

    Traceback (most recent call last):
      File "./run_tutorial_b.py", line 9, in <module>
        y_out = odesolve(m.model, x )
      File "/Users/goldbera/ThirdPartyCode/pysb-1.0.1/pysb/integrate.py", line 335, in odesolve
        solver = Solver(model, tspan, integrator, **integrator_options)
      File "/Users/goldbera/ThirdPartyCode/pysb-1.0.1/pysb/integrate.py", line 87, in __init__
        pysb.bng.generate_equations(model)
      File "/Users/goldbera/ThirdPartyCode/pysb-1.0.1/pysb/bng.py", line 301, in generate_equations
        rule = model.rules[rule_name]
      File "/Users/goldbera/ThirdPartyCode/pysb-1.0.1/pysb/core.py", line 1525, in __getitem__
        return self._map[key]
    KeyError: '_reverse_C8_Bid_bind'

Printing out self._map, one finds the rules tBid_from_C8Bid and C8_Bid_bind, but not _reverse_C8_Bid_bind.

    {'tBid_from_C8Bid': Rule('tBid_from_C8Bid', C8(b=1) % Bid(b=1, S='u') >> C8(b=None) + Bid(b=None, S='t'), kc), 'C8_Bid_bind': Rule('C8_Bid_bind', C8(b=None) + Bid(b=None, S='u') <> C8(b=1) % Bid(b=1, S='u'), kf, kr)}

(The rules have been revised so reactions are connected.)

Looking at the BioNetGen model developed earlier in odesolve() I find the reverse reaction:

    # Created by BioNetGen 2.2.6-stable
    begin parameters
        1 kf       1.000000e-07  # Constant
        2 kr       1.000000e-03  # Constant
        3 kc       1.000000e+00  # Constant
        4 C8_0     1.000000e+03  # Constant
        5 Bid_0    1.000000e+04  # Constant
    end parameters
    begin species
        1 C8(b) C8_0
        2 Bid(S~u,b) Bid_0
        3 Bid(S~u,b!1).C8(b!1) 0
        4 Bid(S~t,b) 0
    end species
    begin reactions
        1 1,2 3 kf #C8_Bid_bind
        2 3 1,2 kr #_reverse_C8_Bid_bind
        3 3 1,4 kc #tBid_from_C8Bid
    end reactions
    begin groups
        1 obsC8                1
        2 obsBid               2
        3 obstBid              4
    end groups

Happy to provide any additional configuration information to debug this.

Regards
Arthur

**Comment by lh64** [comment]
Thanks for the report Arthur. The problem is that the naming convention for reversible reactions was changed in BioNetGen 2.2.6. We have patched it in the repository version of the PySB code but the released version (1.0.1) doesn't yet have this patch. We are actively working on getting a new PySB version out soon that has this patch. However, in the meantime, you can get around this issue either by using BioNetGen version 2.2.5 or by using the repository version of PySB. If you have any problems with either of these solutions please let us know.

**Comment by artgoldberg** [comment]
Thanks Leonard

We’ll try your suggestions.


On Feb 29, 2016, at 11:00 PM, Arthur Goldberg <artg@cs.nyu.edu> wrote:




-------- Forwarded Message --------
Subject:        Re: [pysb] Unable to run reversible reactions (#191)
Date:   Mon, 29 Feb 2016 17:17:38 -0800

**Comment by jmuhlich** [comment]
In the next week or so we'll be releasing pysb v1.1.0 which includes this fix.
