### ISSUE TITLE
document BNGPATH environment variable

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#198]
We need to document this so users know how to point to a BNG distribution in a location other than the places PySB looks for it by default.

**Comment by adelq** [comment]
I believe this is documented in the [install docs]( https://github.com/pysb/pysb/blob/eca58155e16c651ebf3477919c94740ee7a9efb7/doc/installation.rst#required-software) as of the current revision

**Comment by jmuhlich** [comment]
You are absolutely right, thanks!
