### ISSUE TITLE
Travis build intermittently fails due to Kappa test_flux_map

### ISSUE THREAD

**Issue by alubbock** [pysb/pysb#211]
The unit test suite seems to occasionally fail on Travis with the following Exception:
```
======================================================================
FAIL: Test kappa simulation with flux map (returns tuple with graph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pysb/pysb/build/lib/pysb/testing/__init__.py", line 16, in inner
    func(*args, **kwargs)
  File "/home/travis/build/pysb/pysb/build/lib/pysb/tests/test_kappa.py", line 64, in test_flux_map
    ok_(len(simdata['time']) == 101)
AssertionError: None
```

The error looks to be intermittent - my recent pull request generated the error, but re-running the test suite with the PySB code unchanged made it disappear.

An example of the unit test failure is here (please don't re-run that Travis job; we should keep it to diagnose the problem):
https://travis-ci.org/pysb/pysb/jobs/124780210

**Comment by alubbock** [comment]
FWIW I've only observed this on Python 2.7 builds.

**Comment by johnbachman** [comment]
Yes, I have definitely noticed that. I'm honestly baffled.
