### ISSUE TITLE
Invalid Syntax in hello_pysb.py

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#222]
Hello community,

I installed pysb trough terminal using pip and pip3. Then, I run the hello_pysb.py script found in https://github.com/pysb/pysb/blob/master/pysb/examples/hello_pysb.py. However, python found a syntax error at the ">" symbol in Rule('L_binds_R', L(s=None) + R(s=None) <> L(s=1) % R(s=1), kf, kr).

What did I done wrong?

Thanks!

**Comment by jmuhlich** [comment]
Hi, for Python 3 you'll need to edit the `<>` operator to `!=`. We originally supported just Python 2 and chose `<>` to represent bidirectional reactions before realizing Python 3 changed it to `!=`. We need to explain this in the documentation!
