### ISSUE TITLE
pysb compatibility with python3

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#226]
Hello everyone,

A few days ago, I posted an issue with python3 in which <> symbols where replaced with !=. That worked fine and I constructed my first model, running on python3. However, I realize that maybe the "ANY" could also be replaced from python2 to python3. Is it the case??

Thank you and best regards!

**Comment by jmuhlich** [comment]
`pysb.ANY` is not the same thing as the python built-in `any`! `pysb.ANY` is used when writing a MonomerPattern where you want to indicate that a site must be bound, but you want to allow the other agent to be anything. For example:
```python
A(x=None, y=ANY)
```
This will match an `A` monomer with its `x` site unbound and its `y` site bound to anything.

**Comment by glucksfall** [comment]
Yes, I understand. However, when I try to use ANY (`Initial(LacY(Met_BD_01 = None, Met_BD_02 = None, Open = ANY)`), python retrieve an error `NameError: name 'ANY' is not defined`. So... What am I doing wrong?? Is it there any library that I need to import?

Thanks

**Comment by JamesPino** [comment]
Did you do import via "from pysb import ANY "?

**Comment by glucksfall** [comment]
Ok... thanks, that's was the problem. I was trying to import ANY through `from pysb import core`. Now it works perfectly.

**Comment by johnbachman** [comment]
If you do "from pysb import *" that will bring in the core components, plus ANY and WILD, from core (but not the internal helper classes).
