### ISSUE TITLE
Function in Expression

### ISSUE THREAD

**Issue by SMV818VMS** [pysb/pysb#243]
I am exploring how to use custom reaction rates in a rule and I have found this problem.

Let's imagine I want R produced based on a custom rate fitting a sigmoid function:
P(R) = 1 / (1+e(^-Rcurrent))

I build the model like:

```python
from pysb import *
from math import exp

# Start the model
Model()

# Define the species taking part in the model
Monomer('R')

# Define initial values for our variables
Initial(R(), Parameter('R_0', 10))

# Observables
Observable('obsR', R())

# Custom rate
Expression('Ksyn', 1/(1 + exp(obsR)))
Rule('R_production', 
     None >> R(),
     Ksyn)
```

This returns the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-4d76bef7dac7> in <module>()
     15 
     16 # Custom rate
---> 17 Expression('Ksyn', 1/(1 + exp(obsR)))
     18 
     19 Rule('R_production', 

/usr/local/lib/python2.7/dist-packages/sympy/core/expr.pyc in __float__(self)
    224         if result.is_number and result.as_real_imag()[1]:
    225             raise TypeError("can't convert complex to float")
--> 226         raise TypeError("can't convert expression to float")
    227 
    228     def __complex__(self):

TypeError: can't convert expression to float
```

The same happens using user defined functions:

```python
from pysb import *
from math import exp

def user_defined_function(x):
    return exp(1-x)

# Start the model
Model()

# Define the species taking part in the model
Monomer('R')

# Define initial values for our variables
Initial(R(), Parameter('R_0', 10))

# Observables
Observable('obsR', R())

# Custom rate
Expression('Ksyn', user_defined_function(obsR))
Rule('R_production', 
     None >> R(),
     Ksyn)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-ee7e861925f6> in <module>()
----> 1 Expression('Ksyn', user_defined_function(obsR))

/usr/local/lib/python2.7/dist-packages/sympy/core/expr.pyc in __float__(self)
    224         if result.is_number and result.as_real_imag()[1]:
    225             raise TypeError("can't convert complex to float")
--> 226         raise TypeError("can't convert expression to float")
    227 
    228     def __complex__(self):

TypeError: can't convert expression to float
```

The only solution I have been able to find is using no functions:

```python
from pysb import *

# Start the model
Model()

# Define the species taking part in the model
Monomer('R')

# Define initial values for our variables
Initial(R(), Parameter('R_0', 10))

# Observables
Observable('obsR', R())

# Custom rate
Expression('Ksyn', 1/(1 + 2.71828**(obsR)))

Rule('R_production', 
     None >> R(),
     Ksyn)
```

Is there any way to formulate custom expressions using a function in the description?

**Comment by bgyori** [comment]
I think the issue is that Expressions have to use symbolic (`sympy`) expressions. You could use the exponential function from `sympy`: http://docs.sympy.org/latest/modules/functions/elementary.html
instead of from `math`.

**Comment by SMV818VMS** [comment]
Nice, using simpy functions fixes the problem.

Thank you very much for the help!

**Comment by jmuhlich** [comment]
Two notes on this:

1. To elaborate a bit on bgyori's comment: pysb's `Parameter`, `Observable` and `Expression` classes all subclass `sympy.Symbol`, so anything that works with sympy's operator overloading to produce a `sympy.Expr` will work when defining a sympy `Expression`. `math.exp` is a normal python function so the sympy operator overloading can't "see" it. Using `math.e**x` or `sympy.exp(x)` will both work, as you and bgyori have shown.

2. Remember that when using an `Expression` in place of a `Parameter` for a rule's rate, the expression will still be multiplied by the amount of each reactant to calculate the overall rate of the reaction(s). You have a synthesis reaction with zero reactants so this doesn't apply here, but it's worth keeping in mind.
