### ISSUE TITLE
Simulator.run modifies the state of the simulator

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#267]
After showing users the new `Simulator` class, I have found they are surprised and dismayed to discover that passing tspan, initials or param_values to `run` causes those values to persist in that simulator instance. I'd like to look at whether we can refactor `run` so it has no side effects. That might be a good time to revisit the overall logic flow in the `initials` and `param_values` getters and setters, as they have grown rather hairy to support a large matrix of use cases.

**Comment by alubbock** [comment]
This is documented in `ScipyOdeSimulator.run`, but I agree it's undesirable and should be changed.
