### ISSUE TITLE
Subscript of dict_values object in simulator/base causes error in Python 3

### ISSUE THREAD

**Issue by johnbachman** [pysb/pysb#270]
See https://github.com/pysb/pysb/blob/master/pysb/simulator/base.py#L188

**Comment by bgyori** [comment]
Actually many other parts of the code are incompatible with python 3. You need to run 2-to-3 conversion first (like Travis does) to get things to work. In this specific example that will put a list() around values() so that you can index it.

**Comment by jmuhlich** [comment]
Yes, please use `pip install .` to install directly from a git checkout under python 3. We need to re-fix a bunch of py3 issues in the code that are being masked because the lib2to3 fixers are somehow all getting run now on install (and thus in Travis testing). That problem is tracked in #271 .

**Comment by jmuhlich** [comment]
Once we fix #271, you will again be able to use `pip install -e .` or `python setup.py develop` under python 3.
