### ISSUE TITLE
all lib2to3 fixers erroneously applied on build, not just fix_ne

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#271]
As of our Python 3 support in #124, we should have only Python-3-compatible source code committed to the repository with one exception: The use of `<>` in example models. setup.py has some logic to apply only the `fix_ne` lib2to3 fixer at build time to deal with this one issue on py3 builds. However it appears that two related issues have arisen: Non-Python-3-compatible code is being committed, and now all of the lib2to3 fixers are being run. I had expected CI to catch Python 3 compatibility issues, but lib2to3 is cleaning them all up before running tests.

We'll need to determine why all the fixers are now running and again disable everything but `fix_ne`, then fix up all py3 problems in our code.

**Comment by jmuhlich** [comment]
#312 will resolve this, but once #309 lands we should drop the 2to3 fixers entirely.

**Comment by alubbock** [comment]
Implemented in #312 (#309 is already merged). We now have native Python 3 compatibility, no fixers required.
