### ISSUE TITLE
Expression in observables

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#288]
Hello,

I have a doubt how to write the following `pysb.Observable('PGA2PGA3', pga2() + pga3())` to produce `%obs: 'PGA2PGA3' (|pga2()| + |pga3()|)` kappa code

Thank you for any suggestion

**Comment by bgyori** [comment]
I was looking for something similar recently. It looks like these lines: https://github.com/pysb/pysb/blob/85625b234bfb86fe91db859bd71fbc05fcad5c30/pysb/generator/kappa.py#L118-L127
currently produce a comma separated list of the terms of the reaction pattern, whereas the arithmetic expression you give above would actually work with KaSim. Should I try implementing this in the KappaGenerator, or is there some reason we shouldn't pursue this?

**Comment by jmuhlich** [comment]
What does `|pga2()| + |pga3()|` mean for the Kappa observable? I can't find any documentation on that syntax.

**Comment by bgyori** [comment]
The preferred representation for amounts is now to put |-s around the monomer, and you can define algebraic expressions of these to observe. Relevant documentation in this section: http://dev.executableknowledge.org/docs/KaSim-manual-master/KaSim_manual.htm#x1-320003.5
