### ISSUE TITLE
export fails if file has dots

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#308]
Hello everyone,

I've crossed with a weird issue. When trying to export (to kappa) the file `setting01.plasmid.without.negativefeedback.py` pysb.export fails with

```
Error in model script:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pysb/export/__main__.py", line 53, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.6/dist-packages/pysb/export/__main__.py", line 37, in main
    model_module = __import__(model_name)
ModuleNotFoundError: No module named 'setting01'
```

while the renamed file `setting01_plasmid_without_negativefeedback.py` is exported without problems. The problem arises in python2 and 3.

Thank you in advance if you solve this small issue

**Comment by bgyori** [comment]
I think the general issue (not related to PySB) is that if you have dots in your filename and then try to import from it. Python interprets the dots as submodule separators, hence the error: `ModuleNotFoundError: No module named 'setting01'` which is the part before the first dot.

**Comment by jmuhlich** [comment]
Yes, it's generally not advised to use dots in filenames for python code for this reason. How have you been importing this model from your other scripts? I suspect that this would not work either:
```python
from setting01.plasmid.without.negativefeedback import model
```
and this is a Python issue, not a PySB one.
