### ISSUE TITLE
Should ComplexPattern compartment default to None?

### ISSUE THREAD

**Issue by bgyori** [pysb/pysb#310]
I was trying to make a ComplexPattern out of a MonomerPattern and got this error:
```
TypeError: __init__() missing 1 required positional argument: 'compartment'
```
Looks like the constructor of ComplexPattern requires the `compartment` argument:
```
ComplexPattern(monomer_patterns, compartment, match_once=False)
```
Would it be okay to make this default to None, i.e. change the arguments to
```
ComplexPattern(monomer_patterns, compartment=None, match_once=False)
```
If yes, I can PR this.

**Comment by lh64** [comment]
You can use the as_complex_pattern() function to convert a MonomerPattern into a ComplexPattern without having to specify the compartment.

**Comment by bgyori** [comment]
Sure, this is not really a problem in that I can just pass an extra `None` when calling the constructor or use the function you suggested. I was just wondering if the argument should be made optional with `None` as default. This is not a big issue...

**Comment by jmuhlich** [comment]
The general pattern I've tried to apply when designing these interfaces is as follows:
* The `Component` subclass constructors offer default values for lesser-used arguments and other general "ergonomic" design features to make life easier for model authors and consumers.
* Other constructors which are usually only called by pysb internals, advanced macro authors, or other "systems" applications have very explicit constructors.
The Pattern constructors fall into the latter category.

**Comment by jmuhlich** [comment]
And yeah, Leonard is correct, `as_complex_pattern` is intended for use in macros or other situations where you want to "up-cast" user input to a `ComplexPattern`.

**Comment by bgyori** [comment]
Okay, got it! I'll close this then.
