### ISSUE TITLE
symbolic functions wrongly exported to kappa

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#333]
Hello,

I declared the following in PySB `Expression('term', -1 + sympy.sqrt(1 + 8 * RT / KD))` and it is exported as `%var: 'term' -1 + sqrt(1 + 8*'RT'*'KD'^(-1))` while it should be `%var: 'term' -1 + [sqrt](1 + 8*'RT'*'KD'^(-1))`. Issue tested with kasim3 and kasim4 (checkout d69ddb6)

Best regards

**Comment by alubbock** [comment]
Hi @glucksfall, I've posted a fix for this in pull request #334, which also includes Kappa 4 support. When that gets merged, your issue should be resolved.
