### ISSUE TITLE
Synthesis reaction with multiple products, kappa 4 support

### ISSUE THREAD

**Issue by webermarcolivier** [pysb/pysb#338]
I want to define a reaction that synthesizes two products. In kappa 4.0, the syntax is:
```
'synthesize_A_and_B' M(),.,. -> M(),A(),B() @ 'k'
```

However, the same reaction in pysb converted to kappa model produces only one ghost agent (dot) instead of two. Minimal example:
```python
from pysb import *
from pysb import kappa
from pysb.export import export
from pysb.kappa import run_simulation

Model()
Monomer('A')
Monomer('B')
Monomer('M')
Parameter('k', 3.0)
Rule('synthesize_A_and_B', M() + None + None >> M() + A() + B(), k)

kappaModel = export(model, 'kappa')
with open('model.kappa', 'w') as f:
    f.write(kappaModel)

run_simulation(model, time=10, points=10, verbose=True)
```
Exported kappa file:
```
%agent: A()
%agent: B()
%agent: M()

%var: 'k' 3.000000e+00

'synthesize_A_and_B' M(),. -> M(),A(),B() @ 'k'
```
When running KaSim raises the error:
```
Left hand side/right hand side agent mismatch
```
This happens even when forcing the evaluation order with parenthesis `(M() + None) + None` to prevent `None + None` to be evaluated first.
Is this an inherent limitations in pysb syntax? Or a bug in the support for Kappa 4 syntax (see pull request https://github.com/pysb/pysb/pull/334)?

**Comment by alubbock** [comment]
Hi Marc,

Thanks for bringing this to my attention - it does indeed look like a bug in the interface. I'm working on a fix now.

Thanks,
Alex
