### ISSUE TITLE
Bug in pySB1.6.0 exporting expressions as Kappa

### ISSUE THREAD

**Issue by gwebster** [pysb/pysb#345]
In pySB 1.6.0 there seems to be an issue exporting expressions (at least as Kappa). If the name of one term in the expression is the stem of the name of a subsequent term, for example: ‘cell_volume’ and ‘cell_volume_fraction’ - the second term gets mangled in the export as shown below. When I change the names of the expression terms to break this condition, the export seems to work as expected.

```
--- pySB code
Parameter('avogadro', 6.022e23)
Parameter('cell_volume’, 2.25e-12)
Parameter('cell_volume_fraction’, 0.001)
Expression('stochastic', avogadro * cell_volume * cell_volume_fraction)
--- output kappa code
%var: 'stochastic' 'avogadro'*'cell_volume'*'cell_volume'_fraction

--- pySB code
Parameter('avogadro', 6.022e23)
Parameter('alpha', 2.25e-12)
Parameter('beta', 0.001)
Expression('stochastic', avogadro * alpha * beta)
--- output kappa code
%var: 'stochastic' 'avogadro'*'alpha'*'beta'
```

**Comment by alubbock** [comment]
Thanks for your report - there was indeed a bug in PySB's kappa exporter. I've created a fix which will be incorporated into the next release.
