### ISSUE TITLE
Expression doesn't verify its argument is a sympy.Expr

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#349]
`Expression` requires that its `expr` field is a `sympy.Expr`. The constructor doesn't validate this. We should raise a ValueError if another type is passed. It might be OK to automatically convert ints and floats to the corresponding sympy types, but no other automatic conversion should be performed.

**Comment by alubbock** [comment]
I would suggest no automatic conversion. ints and floats are better represented as Parameters, since some simulators don't support Expressions. This choice between Parameter or Expression can be handled within the importer machinery for the SBML/BNGL import cases.
