### ISSUE TITLE
wishlist: check for invalid internal states

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#351]
Hello everyone,

With the transition to kappa syntax 4, we can't longer define an internal state with an integer (https://github.com/Kappa-Dev/KaSim/issues/512). It would be useful to check for validity because this error is raised when calling `kappa.run_simulation` or externally calling KaSim (PD: I did the test with rc1 installed with `conda install -c alubbock kappa`)

**Comment by alubbock** [comment]
Here's an example of what @glucksfall is talking about `Monomer('A', ['a'], {'a': ['1', '2']})`. PySB only accepts strings as state values, but those strings can be anything, including stuff like `')'` which will probably make BNG and Kappa fail.

I think the same applies to site and state names.

We could validate these using a regular expression. I'd suggest the following: `_∗[a-zA-Z][a-zA-Z0-9_]∗`, [which is slightly more restrictive than what Kappa allows](https://tools.kappalanguage.org/docs/KaSim-manual-master/KaSim_manual.htm#x1-80002.1).

Many SBML and BNGL models use numeric state values, however, so I don't think we can make that restriction immediately. I'll make a PR on this with some initial validation, but I'd want to hear @jmuhlich's input on whether numeric state values should be deprecated or generate a warning.

**Comment by lh64** [comment]
Rather than changing the PySB naming conventions, what if we just modify the Kappa exporter to put an underscore or an 'x' or something at the beginning of any numeric state names? Disallowing things like parentheses or other special characters is fine but numeric state values are very common.

**Comment by jmuhlich** [comment]
I propose prefixing with `__` or `__state` for congruence with our general approach of using double-underscore for this sort of thing.

**Comment by alubbock** [comment]
See #352 for a PR which addresses this.

**Comment by jmuhlich** [comment]
Fixed by #352.
