### ISSUE TITLE
BNG error message extraction fails in the face of an underlying Perl warning

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#362]
Saw this today:
> BngInterfaceError: 
> Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^(Rule[0-9]{ <-- HERE .*})r$/ at /home/jmuhlich/apps/BioNetGen-2.3.0/Perl2/Visualization/ProcessGraph.pm line 302.
> ABORT: Reaction rule list could not be read because of errors.

No further error messages were visible in the pysb exception.

Exporting the model to bngl and running BNG2.pl directly gives the full error:
>Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/^(Rule[0-9]{ <-- HERE .*})r$/ at /home/jmuhlich/apps/BioNetGen-2.3.0/Perl2/Visualization/ProcessGraph.pm line 302.
>BioNetGen version 2.3.0
>Reading from file test.bngl (level 0)
>Read 6 parameters.
>Read 3 molecule types.
>Read 3 observable(s).
>Read 3 species.
>ERROR: Molecule created in reaction rule: Component(s) x missing from molecule B()
>  at line 30
>ABORT: Reaction rule list could not be read because of errors.

RuleWorld/bionetgen@46dd2c7d4d19884fdf100174712b5e1711ca625c fixes the Perl warning in BNG but the larger problem in pysb remains.

**Comment by alubbock** [comment]
The error will also be visible if you set the PySB log level to DEBUG. It appears this is unrelated to the perl warning, instead it's down to the way the BNG output is read as a stream during execution, before the BNG exit code is checked.

I'll add some stream parsing to check for errors and warnings as they occur.
