### ISSUE TITLE
While reading observable: edge binds more than 2 components!

### ISSUE THREAD

**Issue by dehlerni** [pysb/pysb#384]
When I run this code:

bind(L(a=None, b=None), 'a', R1(a=None), 'a', [k1, k_1])
bind(L(a=None, b=None), 'b', R2(b=None), 'b', [k2, k_2])
bind_complex(L(a=1, b=None)%R1(a=1), 'b', R2(b=None), 'b', [k3, k_3])
bind_complex(L(a=None, b=1)%R2(b=1), 'a', R1(a=None), 'a', [k4, k_4])

#initial conditions
Parameter('L_0', 100)
Parameter('R1_0', 100)
Parameter('R2_0', 100)
Initial(L(a=None,b=None),L_0)
Initial(R1(a=None), R1_0)
Initial(R2(b=None), R2_0)

#define observables
Observable('obsL', L(a=None,b=None))
Observable('obsR1', R1(a=None))
Observable('obsR2', R2(b=None))
Observable('obsLR1', L(a=1,b=None)%R1(a=1))
Observable('obsLR2', L(a=None,b=1)%R2(b=1))
Observable('obsLR1R2', L(a=1,b=1)%R1(a=1)%R2(b=1))

from pysb.simulator import ScipyOdeSimulator
import pylab as pl

t = pl.linspace(0,720)
simres = ScipyOdeSimulator(model, tspan=t).run()
yout = simres.all

I receive this error message:

BngInterfaceError: 
ABORT: While reading observable obsLR1R2: SpeciesGraph::updateEdges(): edge binds more than 2 components!
  at line 28

It runs fine without the simulation, as well as without the observable "obsLR1R2." Not sure how to resolve the issue otherwise.

Thanks in advance.

**Comment by lh64** [comment]
Hi there. The problem is with how you're defining the observable `obsLR1R2`. Each bond has to have a unique index. Right now, both of the bonds are labeled `1`. Change the Observable definition to `Observable('obsLR1R2', L(a=1,b=2)%R1(a=1)%R2(b=2))` and it should work.

**Comment by dehlerni** [comment]
That did the trick, thank you!
