### ISSUE TITLE
run_tutorial_a is not marked executable

### ISSUE THREAD

**Issue by jmuhlich** [pysb/pysb#413]
@keszybz reported that when building an RPM of PySB, rpmlint complained that the runnable script 
`pysb/examples/run_tutorial_a.py` was not marked +x (the other scripts there are). He filed #104 but it's languished for a couple of reasons. First, the tutorial doc includes that script directly and we thought putting a `#!/usr/bin/env python` at the top would just add noise in that context. Second, I wanted to rethink this approach to the run_* scripts anyway.

I propose actually we *remove* the +x bit and strip the shebang lines from all example run scripts. I don't feel it's that useful to allow them to be directly run -- `python run_foo.py` is fine, and a lot of beginners (for whom the +x simplification was presumably intended) will be using an IDE anwyay.

**Comment by alubbock** [comment]
Agreed
