### ISSUE TITLE
Import of SBML models as black box modules?

### ISSUE THREAD

**Issue by johnbachman** [pysb/pysb#42]
Carlos brought this up the other day. The idea would be to be able to use PySB with existing (non-PySB) SBML models if only so that one could add things to them or compose them within a larger model. Don't know how this would be implemented though in terms of core--would it even be possible to generate BNG for such a model? I imagine that we would have to do some weird things to weld together the reactions generated by BNG and the reactions explicitly encoded in an SBML model. Something to think about though.

**Comment by alubbock** [comment]
PySB now has an SBML importer, including one step loading from Biomodels: http://pysb.readthedocs.io/en/latest/modules/importers/index.html

**Comment by alubbock** [comment]
The SBML importer (linked in my previous message) seems to cover this use case, so I'll close this ticket. Please open a new ticket if there are any specific issues with its use.

Thanks.
