### ISSUE TITLE
Typo in "Creating a model" tutorial under "Rules"

### ISSUE THREAD

**Issue by jadeshi** [pysb/pysb#421]
I noticed that in the "Rules" section of the tutorial, there seems to be a typo/inconsistency in the rule 'C8_Bid_bind' when it is included in the executable mymodel.py script. When first mentioned, the rule is defined as:

Rule('C8_Bid_bind', C8(b=None) + Bid(b=None, S='u') | C8(b=1) % Bid(b=1, S='u'), kf, kr)

with site S in the u state, but immediately following it in mymodel.py the S state is set as None:

Rule('C8_Bid_bind', C8(b=None) + Bid(b=None, S=None) | C8(b=1) % Bid(b=1, S=None), kf, kr)

I'm assuming the correct state should be u?

**Comment by alubbock** [comment]
Yes, it should be 'u'. Thanks for reporting this, I'll get it fixed ASAP.
