### ISSUE TITLE
Stochastic simulation option?

### ISSUE THREAD

**Issue by jadeshi** [pysb/pysb#423]
Would it be possible to add a functionality to perform stochastic simulations instead of only deterministic ones through the ODE solver (e.g. Gillespie's algorithm)?

**Comment by alubbock** [comment]
Hi, this functionality is already in PySB. We actually have interfaces to two implementations of Gillespie's Stochastic Simulation Algorithm (SSA): one based on [StochKit](https://github.com/StochSS/StochKit) and one based on [BioNetGen](https://www.csb.pitt.edu/Faculty/Faeder/?page_id=409).

Example using BioNetGen SSA: https://github.com/pysb/pysb/blob/v1.8.1/pysb/examples/run_bng_ssa_example.py
Example using StochKit SSA: https://github.com/pysb/pysb/blob/v1.8.1/pysb/examples/run_tyson_oscillator_stochkit.py

Documentation on those interfaces is in the [PySB documentation](http://docs.pysb.org/en/stable/modules/simulator.html).

Hope that helps!

**Comment by jadeshi** [comment]
Perfect, this is exactly what I needed, thanks! I think it might be good to highlight these two examples, maybe in a small subsection of "Simulation and Analysis", since it may be useful for others as well!

**Comment by alubbock** [comment]
Updating the tutorial is a good idea. I've added that as a separate issue, #442 

If you have further questions, please check out our chat room on gitter: https://gitter.im/pysb/pysb
