### ISSUE TITLE
Missing sbmlTranslator binary

### ISSUE THREAD

**Issue by maurosilber** [pysb/pysb#459]
Hi!

I freshly installed pysb with conda and the sbml importer fails with the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '[...]/share/bionetgen/bin/sbmlTranslator': '[...]/share/bionetgen/bin/sbmlTranslator'`

Going to that location, the binary is a symbolic link:
`lrwxrwxrwx 1 [...] share/bionetgen/bin/sbmlTranslator -> ../../../bin/sbmlTranslator`
which points to `miniconda3/bin/sbmlTranslator`, which doesn't exist.

By the way, I'm using `pysb.importers.sbml.model_from_biomodels`.

**Comment by ortega2247** [comment]
Hi. PySB uses atomizer to translate sbml models into bionetgen and then translates bionetgen to the pysb format. To get your code working you just need to install atomizer from conda:

conda install -c alubbock atomizer

Maybe we should add this to the documentation @alubbock ??

**Comment by jmuhlich** [comment]
I had no problem just now starting from a fresh conda environment, running `conda install -c pysb`, then executing `pysb.importers.sbml.model_from_biomodels("1")`. Could you please paste the output from the following two commands? (You can redact any information on usernames or paths that you don't want to make public -- I'm mostly looking for versions and platform name).

```
conda info
conda list
```

Thanks.

**Comment by jmuhlich** [comment]
Oops, nevermind my comment, I had a separate full BNG installation (including atomizer) on my path, and pysb was using that. @ortega2247 has the correct solution.

**Comment by maurosilber** [comment]
Great. Installing atomizer fixed it. Thank you, @ortega2247.

If atomizer is an optional dependency, besides adding it to the documentation, you might want to check if it is installed and throw a more meaningful error.

**Comment by alubbock** [comment]
Thanks @maurosilber for the report. I've created a pull request to improve the error message and documentation here: #460.
