### ISSUE TITLE
PySB only shows the BioNetGen error when a rule is not well defined

### ISSUE THREAD

**Issue by ortega2247** [pysb/pysb#465]
When a PySB model has a rule that is not well defined (e.g edge binds more than two components), PySB only shows a BngInterfaceError pointing out the line in the temporal bng file. For users that don't know how PySB works it might be confusing as they don't know that the line is referring to the temporal bngl file and not their actual code. Hence, I was wondering if it would be more useful (if possible) to mention the rule name in the error message.

Example:
```python
from pysb import *
from pysb.bng import generate_equations
Model()
Monomer('a', ['b1', 'b2'])
Monomer('b', ['b1'])
Monomer('c', ['b1'])

Initial(a(b1=None, b2=None), Parameter('a0',1))
Initial(b(b1=None), Parameter('b0',1))
Initial(c(b1=None), Parameter('c0',1))
Parameter('k', 1)

Rule('binding', a(b1=None, b2=None) + b(b1=None) + c(b1=None) >> a(b1=1, b2=1) % b(b1=1) % c(b1=1), k)

generate_equations(model)
``` 
When running this model it throws this error:
BngInterfaceError: ERROR: SpeciesGraph::updateEdges(): edge binds more than 2 components!
  at line 22
ABORT: Reaction rule list could not be read because of errors.

**Comment by alubbock** [comment]
Thanks for the report. We should be trying to catch these sorts of errors in PySB as soon as possible - in this case, when the rule is defined. I've created PR #466 for this case.
