### ISSUE TITLE
change to_matrix() to to_numpy() in pysb/simulator/cupsoda.py

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#514]
Hello,

as_matrix() was deprecated (https://pandas.pydata.org/pandas-docs/version/0.25.2/reference/api/pandas.DataFrame.as_matrix.html) and values() won't work as expected following the pandas' dev suggestion.

Instead, to_numpy() works and produce simulations with cupsoda (https://pandas.pydata.org/pandas-docs/version/0.25.2/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy)

(I made a mistake in the title, sorry)

Best regards

**Comment by JamesPino** [comment]
This issue can be closed, since it's been resolved and merged.
