### ISSUE TITLE
Compartment size as Expression?

### ISSUE THREAD

**Issue by dweindl** [pysb/pysb#524]
PySB does not allow to specify compartment sizes as Expressions:

https://github.com/pysb/pysb/blob/c434f6ab98301beee1bf9d2a5093f0c79da78824/pysb/core.py#L1375-L1376

Is there a specific reason why only Parameters are allowed? It would be convenient if also (constant) Expressions could be provided.

**Comment by jmuhlich** [comment]
There's no good reason! When I originally wrote that code we didn't have Expression support, and we never revisited it once Expressions were introduced. BNG can take a constant expression there, so we can easily fix this.

**Comment by dweindl** [comment]
Thanks @jmuhlich , I'll submit a PR shortly.
