### ISSUE TITLE
PySB fails to load simulations when len(observable.complex_pattern) > 1

### ISSUE THREAD

**Issue by ortega2247** [pysb/pysb#530]
In #502 code was added to calculate the Observable species and coefficients using PySB's built-in pattern matching during the JSON import process. However the PySB's built-in pattern matching doesn't handle patterns that have len(pattern.complex_pattern) > 1. Hence, when simulations are saved with the default options, specifically include_obs_exprs=False, and then someone tries to load that simulation, it would fail. Maybe it would be a good idea that the default option is to include the observables and expressions when saving a simulation?

**Comment by alubbock** [comment]
Hi @ortega2247, do you have a minimal reproducible example of this problem you could share? Thanks

**Comment by ortega2247** [comment]
I just ran my simulations again and can't reproduce the error. I still have the original hdf5 file and i'll take a closer look later this week. Closing this issue for now

**Comment by jmuhlich** [comment]
Is it possible this is intersecting with the change in how we serialize models to the hdf5 file, from pickle to json?
