### ISSUE TITLE
Rule-based modeling with energy descriptions

### ISSUE THREAD

**Issue by himoto** [pysb/pysb#552]
Hello,

Currently, BioNetGen 2.2+ incorporate energy descriptions, in which models satisfy detailed balance constraints.
Will PySB officially support the energy-based modeling, e.g., energy pattern formulation, generating kinetic constants from baseline energies and rate distribution parameters, etc.?

**Comment by jmuhlich** [comment]
I have a branch with energy modeling in progress at Pull Request #553 that you could try out. It should support all energy features that BNG supports. The documentation for the new features doesn't exist yet, but if you are familiar with the BNG energy syntax you should be able to get started.

**Comment by himoto** [comment]
Thank you very much!
I tried it and confirmed that `EnergyPattern` and  energy rules (setting energy in `Rule` to True) worked perfectly fine in it.
As reported in #551, it throws a TypeError when running a simulation with SymPy version 1.9 but worked without any problems with version 1.8.

**Comment by lgerosa** [comment]
Hi @himoto , I have a bunch of toy model examples on how to use Energy PySB in this repository:  [https://github.com/lgerosa/rosa_webinar_20Jan2021](url)
Feel free to contact me in case you have any questions, I am very happy to brainstorm/discuss usages of energy PySB in general.

**Comment by himoto** [comment]
Hello @lgerosa ,
Thank you very much for informing me of the repository. The model examples and slides really helped me learn how to incorporate thermodynamic factors into mechanistic models and write energy rules with PySB.
And I appreciate your kind support. I’ll let you know if I have any questions.
