### ISSUE TITLE
tarballs listed on pypi have unexpected contents

### ISSUE THREAD

**Issue by keszybz** [pysb/pysb#555]
https://pypi.org/project/pysb/#files lists pysb-1.13.1.tar.gz which has some unexpected contents that don't correspond to the 1.13.1 tag in version control:

-pysb-1.13.1/pysb/examples/cc1.py
-pysb-1.13.1/pysb/examples/duplicate_sites.py
-pysb-1.13.1/pysb/examples/run_cc1.py
-pysb-1.13.1/pysb/examples/run_earm_1_0_multi.py
-pysb-1.13.1/pysb/examples/run_robertson_fixed.py

At the same time, other files are missing.

**Comment by jmuhlich** [comment]
Sorry, will fix that and release 1.13.2 in a minute, then yank 1.13.1.

**Comment by jmuhlich** [comment]
The only missing tracked files that might actually belong in the sdist are the .py files in the subdirectories of `pysb/examples/`, and I think we've always been missing those. Everything else is excluded correctly.

The unexpected extra files were untracked stuff from my local testing -- I am so used to having `setuptools_scm` in my other projects which knows how to skip those when building an sdist. We'll switch pysb to `setuptools_scm` soon.

**Comment by jmuhlich** [comment]
OK, this should be all fixed now. Thanks for picking up on this so quickly!
