### ISSUE TITLE
How do I install PySB to use in a script

### ISSUE THREAD

**Issue by TorkelE** [pysb/pysb#590]
Hello,

I have an ubuntu 22 computer, and would like to create a .py script (using python version 3) that uses pysb. I have followed the instructions here: https://pysb.readthedocs.io/en/stable/installation.html. I have installed anaconda. Next, if I do 
```
~/anaconda3/bin$ ./conda list
```
I get a list of packages which include e.g. pysb and bionetgen.

Next, I try running it in python, but it fails:

```
:~/anaconda3/bin$ python
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
:~/anaconda3/bin$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysb'
>>> 
```

It cannot be found. To be honest, I am unsure how to proceed from here. I have tried searching online if there is some special way to make anaconda installed packages available. I only found something about "activating" the environment. I try:
```
:~/anaconda3/bin$ ./conda init
no change     /home/torkelloman/anaconda3/condabin/conda
no change     /home/torkelloman/anaconda3/bin/conda
no change     /home/torkelloman/anaconda3/bin/conda-env
no change     /home/torkelloman/anaconda3/bin/activate
no change     /home/torkelloman/anaconda3/bin/deactivate
no change     /home/torkelloman/anaconda3/etc/profile.d/conda.sh
no change     /home/torkelloman/anaconda3/etc/fish/conf.d/conda.fish
no change     /home/torkelloman/anaconda3/shell/condabin/Conda.psm1
no change     /home/torkelloman/anaconda3/shell/condabin/conda-hook.ps1
no change     /home/torkelloman/anaconda3/lib/python3.11/site-packages/xontrib/conda.xsh
no change     /home/torkelloman/anaconda3/etc/profile.d/conda.csh
modified      /home/torkelloman/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

:~/anaconda3/bin$ ./conda activate base

CondaError: Run 'conda init' before 'conda activate'

:~/anaconda3/bin$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysb'
>>> 
```

But this does not work either.

To be hoenst I have no idea what to do now. If I just want to install pysb so that I can use it in a script (that I later can run using `python3 my_script.py`), how do I do that?

**Comment by jmuhlich** [comment]
Try closing your terminal window and reopening it. You have to do that after the first time you run `conda init`. That should complete the conda initialization, then `conda activate` should work properly.

**Comment by TorkelE** [comment]
I see. Thanks a lot for the quick response, seems to work now!
