### ISSUE TITLE
bind function does not accept bound states

### ISSUE THREAD

**Issue by michael-irvin** [pysb/pysb#61]
This line of code:
    bind(CD95(blig = 1, bfad = None), 'bfad', FADD(brec = None), 'brec', [KF, KR])
generates this output in BNG:

  bind_CD95_FADD:  CD95(blig!1,bfad) + FADD(brec) <-> CD95(blig!1,bfad!1).FADD(brec!1)    KF, KR

which results in this error:

ERROR: SpeciesGraph::updateEdges(): edge binds more than 2 components!
  at line 18

This is a fix:
    bind(CD95(blig = 2, bfad = None), 'bfad', FADD(brec = None), 'brec', [KF, KR])

which yields:
  bind_CD95_FADD:  CD95(blig!2,bfad) + FADD(brec) <-> CD95(blig!2,bfad!1).FADD(brec!1)    KF, KR

The bind function should check for previously specified bonds in the MonomerPattern before assigning a bond number.

**Comment by alubbock** [comment]
I've implemented dangling bond detection in PySB in #328

**Comment by alubbock** [comment]
I'll close this issue due to lack of recent activity, and the fact that the dangling bond detection should've resolved the issue from what @lh64 is saying. Please feel free to reopen the issue if you're still experiencing problems related to this.

Thanks.
