### ISSUE TITLE
cannot run simulations b/c /tmp is not writable in VM

### ISSUE THREAD

**Issue by clopezx** [pysb/pysb#68]
In some cases when people try to run a PySB simulation (for example those in pysb/examples) they will get an error message that they do not have write permissions for the temporary bngl file during network generation.

**Comment by alubbock** [comment]
VM is no longer a supported install method, please see the updated [installation docs](http://pysb.readthedocs.io/en/stable/installation.html) to use Anaconda or Docker. Closing this issue.
