### ISSUE TITLE
Screen resolution is too low in VM

### ISSUE THREAD

**Issue by clopezx** [pysb/pysb#69]
The screen resolution is set too low in the VM. A reasonable resolution of 1024 x 768 would be a better starting point for most people. Instructions on how to change the resolution for VirtualBox should be provided.

**Comment by alubbock** [comment]
VM is no longer a supported install method, please see the updated [installation docs](http://pysb.readthedocs.io/en/stable/installation.html) to use Anaconda or Docker. Closing this issue.
