### ISSUE TITLE
odesolve fails when a parameter name contains 's#' where # is a number

### ISSUE THREAD

**Issue by johnbachman** [pysb/pysb#78]
I had some problems with a simple model that turned out to be due to the use of a parameter with the name 's0_to_s1_k'. (referring to Bax in 'state 1' going to Bax in 'state 2'). The errors arise from the way that the regexps do substitutions in building up the right-hand side of the ODEs. Here is a simple model that recapitulates the error:

from pysb import *
from pysb.integrate import Solver, odesolve
import numpy as np

Model()
Monomer('Bax', ['conf'],
        {'conf': ['s0', 's1', 's2' ,'s3']})
Initial(Bax(conf='s0'), Parameter('Bax_0', 1))
Observable('Baxs0', Bax(conf='s0'))
Rule('s0_to_s1', Bax(conf='s0') >> Bax(conf='s1'), Parameter('s0_to_s1_k', 1))

t = np.linspace(0, 1000)
x = odesolve(model, t) # Will error due to presence of parameter 's0_to_s1_k'

**Comment by jmuhlich** [comment]
Fixed in ae4cfa174163904127381f51cb733c64f3cff1f4.
