### ISSUE TITLE
Error message from stdout/stderr is not returned when KaSim has an error

### ISSUE THREAD

**Issue by johnbachman** [pysb/pysb#82]
Currently, the line that would have passed args to subprocess.Popen to get the stdout and stderr is commented out:

        print "Running kasim"
        p = subprocess.Popen(['KaSim'] + args)
                           #stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        p.communicate()

        if p.returncode:
            raise Exception(p.stdout.read())

As a result, if KaSim errors, the call to p.stdout.read() in the exception handler gives a NoneType exception and doesn't give the error message from KaSim itself.

**Comment by jmuhlich** [comment]
Fixed in the kappa_fixes branch, which has been merged.
