### ISSUE TITLE
pysb.kappa shoud be more intelligent about looking for likely locations of kappa

### ISSUE THREAD

**Issue by johnbachman** [pysb/pysb#83]
We should crib from bng and look for likely install locations or allow the setting of an environment variable.

**Comment by jmuhlich** [comment]
John, we should really do this for v1.1.0. Can you take it on?

**Comment by johnbachman** [comment]
Any suggestions for where to look? Users can download and build KaSim
anywhere.

**Comment by jmuhlich** [comment]
Copy the bng.py BNGPATH handling code, and more or less just change BNGPATH to KAPPAPATH? Not sure if you should leave the default paths (/usr/local/share... and c:\program files\...) or not.

**Comment by jmuhlich** [comment]
Fixed in #200
