### ISSUE TITLE
Michaelis-Menten Kinetics

### ISSUE THREAD

**Issue by kjemmett** [pysb/pysb#85]
Hi, as someone familiar with Python but not so much earlier biochemical modeling tools, PySB looks really cool!

Can PySB be used to simulate Michaelis-Menten kinetics when only the Michaelis constant is known? Looks like there was some discussion of this in #11, any updates?

**Comment by jmuhlich** [comment]
This has been working for a while, we ought to include an example model that demonstrates it though!
